config/routes.rb
Threadless::Application.routes.draw do
  resources :tees

  root :to => "tees#index"

end

app/models/tee.rb
# -*- coding: utf-8 -*-
require 'open-uri'

class Tee < ActiveRecord::Base
  include ThreadlessFeedParser

  validates_presence_of :shirt_id, :name, :image_url, :who, :link
  validates_format_of   :link, :with => URI::regexp(%w(http https))
  validates_format_of   :link, :with => /^(?!(.*\/submission\/.*))/,
                               :message => "El link que estás usando apunta a un submission. Utiliza
                                            el link a la camiseta en sí."
  validates_length_of   :who, :minimum => 3


  # Fetches the shirt id, shirt title and shirt image and returns
  # them as an array (in that order).
  def self.gather_data_from_url(url)
    doc = Nokogiri::HTML(open(url))

    # there are usually 5 ".title" in the doc, push our luck and pick first.
    # span.blue is used in the old Threadless UI (still used for es.threadless.com).
    title_selector = doc.css("h1.title").first || doc.css('span.blue').first
    title = title_selector.content

    # typical URL is http://www.threadless.com/product/2337/Mr_Cloud_s_New_Scarf/trash...
    id = url.split("/")[4]

    # take the first image, it's usually the design without a model
    image = build_shirt_image_url(id)

    [id, title, image]
  end

  # Returns all the tees in the DB without the repetitions that appear when more
  # than one person buys the same shirt.
  # Heroku uses PG which doesn't support the hacky GROUP BY so we use DISTINCT ON()
  def self.unique_tees
    case ActiveRecord::Base.connection.adapter_name
      when "PostgreSQL"
      sql = <<eos
SELECT DISTINCT ON (tees.shirt_id) tees.shirt_id, tees.name, tees.image_url, tees.who, tees.link
 FROM tees;
eos
        Tee.find_by_sql(sql)
      else
        Tee.group("shirt_id")
    end
  end

  # returns a list of tees that no one has bought yet.
  def self.suggested_tees
    Tee.available_tees.shuffle.take(9)
  end

  # Returns the names of all the people who bought this shirt.
  # TODO: Add a new table (UsedBy) with `shirt_id`, and `who` so we don't
  # repeat the records on Tees. That allows us to remove Tee.unique_tees too.
  def bought_by
    Tee.where("shirt_id = #{self.shirt_id}").collect(&:who).uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tees_controller.rb
class TeesController < ApplicationController
  def index
    @tees = Tee.unique_tees
    @available_tees = Tee.suggested_tees
  end

  def new
    @available_tees = Tee.suggested_tees
    @tee = Tee.new(:link => "", :who => "")
  end

  # TODO Clean this mess, seriously.
  def create
    id, name, image_url = Tee.gather_data_from_url(params[:link])
    who = format_username(params[:who])

    @tee = Tee.new(:shirt_id => id, :name => name,
                  :image_url => image_url, :who => who,
                  :link => params[:link])

    if @tee.valid? && @tee.save!
      redirect_to tees_path
    else
      if @tee.link =~ /\/submission\//
        @available_tees = Tee.suggested_tees
        render :new
      else
        raise Exception, "Invalid t-shirt data: #{params[:link]}"
      end
    end
  end

  protected
  # add a @ to the `who` field if it's missing
  def format_username(text)
    text[0,1] == "@" ? text : "@#{text}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to(*args, &block)
    name, url, *rest = args
    if url =~ /threadless\.com/
      super(name, "#{url}?streetteam=febuiles", *rest)
    else
      super(*args, &block)
    end
  end
end

app/helpers/tees_helper.rb
module TeesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeeShare</title>
    <%= stylesheet_link_tag "reset", "application", "navigation" %>
    <%= javascript_include_tag "jquery.min", "rails", "application" %>
    <%= javascript_include_tag "jquery.quicksearch", "jquery.validate", "jquery.autoclear.min" %>
    <%= javascript_include_tag "jquery.pajinate" %>

    <%= csrf_meta_tag %>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/favicon.ico" />
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20442882-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>
  <body>

      <div class="content">
        <%= yield %>
      </div>

    <div class="sidebar">
      <div class="logo">
       <%= link_to image_tag("logo.png"), "/" %>
      </div>

      <div class="new-shirt">
        <%= link_to "Agregar Camisa Nueva", new_tee_path %>
      </div>

      <div class="suggestions">
        <h2>Nadie Tiene Estas Camisas</h2>
        <table>
          <% @available_tees.each_slice(3) do |shirts| %>
          <tr>
            <%= render :partial => "shared/tee", :collection => shirts %>
          </tr>
          <% end %>
        </table>

        <h2>Otros Productos</h2>
        <div class="other-products">
          <%= link_to image_tag("book.png"), "http://www.threadless.com/book" %>
          <h3><%= link_to "The Threadless Book", "http://www.threadless.com/book" %></h3>
          <p>Totalmente recomendado. Incluye algunos de los mejores diseños y ensayos de gente como <span><%= link_to "Seth Godin", "http://sethgodin.typepad.com/" %></span> o <span><%= link_to "Glenn Jones", "http://www.glennz.co.nz/" %></span>.</p>
        </div>


        <div class="github">
          <h2>Código Fuente</h2>
          <%= link_to image_tag("github.png"), "http://github.com/febuiles/teeshare", :title => "Ver código fuente"  %>
          <p class="contact">Para contacto o reporte de problemas haga<span><%= link_to "click aquí", "mailto:federico@mheroin.com" %></span></p>
          <p class="disclaimer">
            Para la construcción de este sitio se consumió <%= link_to "heroína", "http://mheroin.com" %>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_search.html.erb
<div class="search">
  <input type="text" id="search" title="Buscar" class="auto-clear" />
  <input type="image" src="/images/search.png" class="search-button" />
</div>

app/views/shared/_tee.html.erb
<td class="suggested-shirt">
  <%= link_to image_tag(tee.image_url), tee.link %>
  <span><%= link_to tee.name, tee.link %></span>
</td>

app/views/tees/_shirt.html.erb
<div class="shirt">
  <%= link_to image_tag(shirt.image_url), shirt.link %>
  <h2><%= link_to shirt.name, shirt.link %></h2>
    <ul>
      <% shirt.bought_by.each do |name| %>
      <li><%= link_to name, "http://twitter.com/#{name.delete('@')}" %></li>
      <% end %>
    </ul>
</div>

app/views/tees/index.html.erb
<div class="about">
  <p>En TeeShare compartimos lo que hemos comprado en <%= link_to "Threadless", "http://threadless.com" %>, así no repetimos camiseticas.</p>
</div>


<%= render :partial => "shared/search" %>

<div class="page_content">
  <div class="shirts">
    <%= render :partial => "shirt", :collection => @tees %>
  </div>
  <div class="page_navigation"></div>
</div>
<script type="text/javascript">
  $("input#search").quicksearch("div.shirt");
  $("input.auto-clear").autoclear();
  doPaginate();

  $("#search").keyup(function() {
    if ($(this).val() === "") {
      doPaginate();
    }
  });


</script>

app/views/tees/new.html.erb
<%= form_tag tees_path, :id => "new_tee_form", :method => :post do %>
  <% if @tee && @tee.errors %>
    <% @tee.errors[:link].each do |msg| %>
      <span class="errors"><%= msg %></span>
    <% end %>
  <% end %>


  <div class="field">
    <h2>Link a la camiseta</h2>
    <input type="text" required="true" name="link" id="link" value="<%= @tee.link %>" />
  </div>


  <div class="field">
    <h2>¿Cuál es tu usuario de Twitter?</h2>
    <input type="text" required="true" name="who" id="who" value="<%= @tee.who %>"/>
  </div>

  <div class="actions">
    <%= link_to_function "Guardar", "$('#new_tee_form').submit();" %>
  </div>
<% end %>

<script type="text/javascript">
  $.extend($.validator.messages, {
        required: "Este campo es obligatorio",
        minlength: "Mínimo 3 caracteres"
    });
  $("form").validate({
    rules : {
    who : {
      minlength: 3
    }}
  });

  $(function() {
    $("form input").keypress(function (e) {
      if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
        $('form').submit();
        return false;
      } else {
        return true;
      }
     });
  });

</script>